type: S3
config:
  bucket: bucket-name-fill
  endpoint: endpoint-url-fill
  secret_key: secret-key-fill
  access_key: access-key-fill
  insecure: true
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 2m
    insecure_skip_verify: true
  trace:
    enable: true